config/routes.rb
Rails.application.routes.draw do

  get 'templates/floating_menu'

  get 'billing_reports/payments' => 'billing_reports#payments', as: 'payments_datatable'
  get 'billing_reports/payments_summary' => 'billing_reports#payments_summary', as: 'payments_summary'
  get 'billing_reports/weekly_bills_summary'
  get 'billing_reports/receivables_summary'
  get 'bills/index_report_bills'
  get 'fetch_bill_paid_amount' => 'bills#fetch_bill_paid_amount', as: 'fetch_bill_paid_amount'

  resources :bonuses
  resources :payments
  resources :on_calls do
    resources :comments
  end
  resources :claim_types
  resources :payment_types
  resources :availabilities
  resources :insurance_companies
  resources :reimbursement_timesheets do
    resources :comments
  end

  get 'bills/delete_all_bills' => 'bills#delete_all_bills'
  resources :bills do
    resources :payments
    collection do
      post :import
      get :reports
      get :receivables
    end
  end

  resources :reports do
    member do
      get :generate_instance
      get :export
    end
    collection do
      get :get_form_fields
      get :get_field_aliases
      get :get_field_basic_types
    end
  end

  resources :notifications, only: [:index] do
    collection do
      post :mark_all_as_read
      get :mark_as_read
    end
  end

  resources :hour_types
  resources :hours do
    resources :comments
  end

  get 'show_patients_forms' => 'admin_patients#show_patients_forms', as: 'show_patients_forms'
  
  resources :admin_configurations, only: [:index, :update]

  namespace :admin do
    get :users
    put :update_users_roles_permissions
    get :patients
    put :update_patients_roles_permissions
    put :timesheets
    put :update_timesheets_roles_permissions
    get :visits
    put :update_visits_roles_permissions
    get :bills
    put :update_bills_roles_permissions
  end

  resources :coverage_areas

  resources :agencies

  resources :visits do
    resources :comments
    get :add_reimbursement
  end

  resources :visit_types

  resources :reimbursements

  resources :diseases

  resources :departments

  get 'reports/get_total_report'

  get 'create_timesheet' => "timesheets#create_timesheet", as: 'create_timesheet'

  mount CustomForms::Engine => '/'

  get 'timesheets/update_task_state', as: 'update_task_state'

  get 'timesheets/latest' => 'timesheets#show_latest', as: 'latest_timesheet'
  get 'employees_timesheets' => 'timesheets#employees_timesheets', as: 'employees_timesheets'
  
  resources :timesheets, only: [:index, :show, :update] do
    resources :comments
    member do
      put :submit
      put :admit
      put :pay
      get :send_email_to_owner
    end
  end
  put 'timesheets' => 'timesheets#index' 
  resources :payrolls do 
    member do
      get 'payroll_statistics/get_exceeded_employees', as: 'get_exceeded_employees'
      get 'payroll_statistics/show_employees_visits_per_patient', as: 'show_employees_visits_per_patient'
      get 'payroll_statistics/show_top_ten_employees', as: 'show_top_ten_employees'
      get 'payroll_statistics/show_employees_with_reimb', as: 'show_employees_with_reimb'
      get 'payroll_statistics/show_employees_with_over_time', as: 'show_employees_with_over_time'
      
    end
  end

  resources :roles

  resources :user_documents

  resources :document_types

  get 'admin/index'

  resources :license_types

  resources :job_types

  get "find_patients_matches" => "patients#find_patients_matches", as: "find_patients_matches"
  get 'patients/delete_all_patients' => 'patients#delete_all_patients', as: "delete_all_patients"
  resources :patients do
    put :update_forms, on: :member
    get :get_patient_data
  end

  get 'scrape_users' => 'users#scrape_users'
  get 'scrape_agencies' => 'agencies#scrape_agencies'
  get 'scrape_patients' => 'patients#scrape_patients'
  get 'scrape_visits' => 'visits#scrape_visits'

  root 'users#index'
  devise_for :users, controllers: { registrations: 'users' }
  resources :users, except: :destroy do
    put :update_forms, on: :member
    post :reset_password_via_email
    resources :timesheets, only: [:index, :show, :update] do
      member do
        put :submit
        put :admit
        put :pay
      end
    end
    member do
      post :deactivate_user
      post :activate_user
      put :update_password
    end
    resources :visits
  end

  get 'edit_roles' => 'users#edit_user_roles', as: 'edit_user_roles'
  put 'update_user_role' => 'users#update_user_role', as: 'update_user_role'

  get 'view_assigned_visits' => 'visits#view_assigned_visits', as: 'view_assigned_visits'
  get 'get_visit_type_dependant_data' => 'visit_types#get_visit_type_dependant_data', as: 'get_visit_type_dependant_data'

  get 'static_page/:page' => 'static#show'
  get 'show_comments' => 'visits#show_comments'

end

app/models/visit.rb
class Visit < ActiveRecord::Base
  # constants
  PROGRESS_STATE = %w(unassigned assigned visited missed pending approved admited paid rejected)

  # associations
  belongs_to :assigner, class_name: 'User', foreign_key: 'assigner_id'
  belongs_to :assignee, class_name: 'User', foreign_key: 'assignee_id'
  belongs_to :patient
  belongs_to :visit_type
  belongs_to :agency
  has_many :reimbursements_visits
  has_many :reimbursements, through: :reimbursements_visits
  accepts_nested_attributes_for :reimbursements_visits, allow_destroy: true
  has_many :comments, :as => :commentable, dependent: :destroy
  belongs_to :timesheet
  has_many :notifications, :as => :notifiable, dependent: :destroy
  
  # callbacks
  before_save :init_progress_state
  after_create :create_reimbursements

  # validations
  validates :visit_type_id, presence: true
  validates :assignee_id, presence: true

  # scope
  scope :user_visits, ->(assignee_id) { where(assignee_id: assignee_id) }
  scope :price_editable_visits, -> {where(progress_state: ['unassigned', 'assigned', 'visited', 'missed', 'pending'])}

  require 'httparty'
  require 'mechanize'

  def self.scrape_visits
    run_visits_scraper
  end

  def update_visit_total_price
    if ['unassigned', 'assigned', 'visited', 'missed', 'pending'].include? self.progress_state
      total_price = self.reimbursements_visits.map do |rv|
 
        rv.action_count *  rv.reimbursement.riembursement_price(self.assignee)
      end
      reimbursements_price_sum = 0
      reimbursements_price_sum = total_price.inject{|reimbursements_price_sum, e| reimbursements_price_sum + e } || 0
      visit_total_price = reimbursements_price_sum + self.visit_price
      self.update_attribute(:total_price, visit_total_price)
    end

  end

  def visit_price
    if self.assignee
      self.assignee.payment_rates.find_by(visit_type_id: self.visit_type.try(:id)).try(:price) || self.visit_type.try(:price)
    else
      0
    end
  end

  def price
    price = visit_price
    self.reimbursements.each do |r|
      price = price + r.price
    end
  end
  def user
    self.assignee
  end

  def set_reimbursements
    self.visit_type.reimbursements.each do |reimbursement|
      
      self.reimbursements << reimbursement unless self.reimbursements.include? reimbursement
    end
  end

  private

  def tiem_in_type
    self.time_in.is_a? Time 
  end

  def tiem_out_type
    self.time_out.is_a? Time 
  end

  # validate that progress state is valid 
  def validate_progress_state
    errors.add(:progress_state, 'is invalid') unless (PROGRESS_STATE.include? self.progress_state)  || (self.progress_state == nil)
  end

  def init_progress_state
    unless self.progress_state 
      if self.assignee
        self.progress_state = 'visited'
      else
        self.progress_state = 'unassigned'
      end
    end
  end
    
  def create_reimbursements
    self.visit_type.reimbursements.each do |reimbursement|
      self.reimbursements << reimbursement
    end
  end

  def self.run_visits_scraper
    Mechanize.start do |agent|
      agent.get('https://prohealth.devero.com/login.action')
      form = agent.page.forms.first
      form.username = 'egypt'
      form.password = 'login1!2!'
      form.submit

      @hsession_key = agent.page.uri.to_s.split('hhsosSessionKey=').last.split('&').first
      @jsession_id = agent.cookie_jar.to_a.first.value
      @hhsosTokenKey = agent.page.search("[name='hhsosTokenKey']").first.attributes['value'].value
      page = Visit.get_page(agent, '1')

      pages = page.search('.numPages').last.text
      (1..pages.to_i).each do |index|
        table_rows = page.search('#reportTbl tbody tr')
        table_rows.each_with_index do |row, _row_ind|
          visit = {}
          patient = {}
          row.search('td').each_with_index do |cell, i|
            case i
            when 0
              patient[:display_name] = cell.text.strip
            when 1
              patient[:medical_record_number] = cell.text.strip
            when 2
              status = StatusChart.where(name: cell.text).first_or_create
              patient[:status_chart_id] = status.id
            when 3
              agency = Agency.find_by(name: cell.text.strip)
              visit[:agency_id] = agency.try(:id)
              patient[:agency_id] = agency.try(:id)
              # when 4
              # patient.merge! insurance: cell.text.strip.strip
            when 5
              visit_type = VisitType.where(title: cell.text.strip, price: 0).first_or_create

              visit[:visit_type_id] = visit_type.id
            when 6
              visit[:form_status] = cell.text.strip 
            when 7
              visit[:date] = Date.parse(cell.text).strftime('%Y-%m-%d')
            when 8
              visit[:assignee_id] = User.find_by(display_name: cell.text).try(:id)
            when 11
              visit[:billing_code] = cell.text.strip
            when 12
              visit[:time_in] = (cell.text).to_time if cell.text.present?
            when 13
              visit[:time_out] = (cell.text).to_time cell.text.present?
            end
          end
          patient[:email] = "#{patient[:display_name].parameterize}@prohealth.com"
          patient = Patient.where(patient).first_or_create
          visit[:patient_id] = patient.id
          visit[:progress_state] = "visited"
          visit[:total_price] = "0"
          visit = Visit.where(visit).first_or_create
          if visit.persisted?
            puts "visit created #{visit.inspect}"
            unless visit.visit_type.job_types.include? visit.assignee.job_type
              visit.visit_type.job_types << visit.assignee.job_type
            end
          else
            puts "error in scrapping #{visit.errors.full_messages.to_sentence}"
          end
        end
        page = Visit.get_page(agent, (index + 1).to_s) if page.search('.nextLink').any?
      end
    end
  end

  def self.get_page(agent, page_num)
    number_of_entries = Rails.env.development? ? '100' : '1000'
    agent.post('https://prohealth.devero.com/runReport.action',
               hhsosSessionKey: @hsession_key,
               hhsosTokenKey: @hhsosTokenKey,
               desc: '1',
               endDate: Time.now.strftime("%m/%d/%Y"),
               mainMenuForward: 'adminMenu.action',
               maxResults: number_of_entries,
               nextStart: '100',
               order: 'visitDate',
               pagingPageNum: page_num,
               previousStart: '0',
               printType: 'specified',
               pushType:  'selectedUsers',
               reportId:  '17',
               selectedActivityStatuses: 'Submitted,Resubmitted,Cosigning,Shared,Pending,Reviewed,Completed',
               selectedFormIds: '73,108,109,76,123,114,110,111,81,82,179,174,64,66,67,142,68,65,69,70,143,71,129,135,130,131,133,134,181,177,83,84,136,132,112,113,117',
               selectedMarkAsFilter3: 'both',
               selectedPatientId: '-1',
               selectedUserId: '-1',
               sendType: 'push',
               start: '0',
               startDate: '11/25/2010')
  end
end

app/models/visit_type.rb
class VisitType < ActiveRecord::Base
  # associations
  has_many :visits
  has_many :payment_rates
  has_many :job_types_visit_types
  has_many :job_types, through: :job_types_visit_types
  has_and_belongs_to_many :departments
  has_and_belongs_to_many :reimbursements

  # validations
  validates :title, presence: true, length: { maximum: 60 }
  validates :price, presence: true
  validates :price, numericality: { greater_than_or_equal_to: 0 }, if: lambda { |object| object.price.present? }

  # callbacks
  after_save :update_visit_reimbursments
  after_save :update_visit_prices


  private
  #TODO_PROHEALTH move to delayed job
  def update_visit_prices
    self.visits.price_editable_visits.each do |visit|
      visit.update_visit_total_price
    end
  end

  def update_visit_reimbursments
    self.visits.each do |visit|
      visit.set_reimbursements
    end
  end
end

app/controllers/visits_controller.rb
class VisitsController < ApplicationController
  before_action :set_visit, only: [:show, :edit, :update, :destroy, :show_comments]
  skip_authorize_resource

  # GET /visits
  # GET /visits.json
  def index
    authorize! :view_all, Visit
    respond_to do |format|
      format.html
      format.json { render json: VisitDatatable.new(view_context) }
    end
  end

  # GET /visits/1
  # GET /visits/1.json
  def show
    set_reimbursements
  end

  # GET /visits/new
  def new
    authorize! :edit, Visit
    @visit = Visit.new
  end

  # GET /visits/1/edit
  def edit
    authorize! :edit, Visit
    @timesheet_id = params[:timesheet_id] || nil
    set_reimbursements
    respond_to do |format|
      format.html
      format.js
    end
  end

  # POST /visits
  # POST /visits.json
  def create
    authorize! :edit, Visit
    @visit = Visit.new(visit_params)
    @visit.assigner = current_user
    respond_to do |format|
      if @visit.save
        format.html { redirect_to @visit, falsh: { success: 'Visit was successfully created.' } }
        format.json { render json: @visit}
      else
        format.html { render :new }
        format.json { render json: @visit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /visits/1
  # PATCH/PUT /visits/1.json
  def update
    @visit.assigner = current_user
    respond_to do |format|
      if @visit.update(visit_params)
        format.html { redirect_to @visit, falsh: { success: 'Visit was successfully updated.' } }
        format.json { render :show, status: :ok, location: @visit }
        if params[:timesheet_id]
          format.js {redirect_to timesheet_path(id: params[:timesheet_id])}
        else
          format.js
          format.json { render json: @visit}
        end
      else
        format.html { render :edit }
        format.json { render json: @visit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /visits/1
  # DELETE /visits/1.json
  def destroy
    @visit.destroy
    respond_to do |format|
      format.html { redirect_to visits_path, falsh: { success: 'Visit was successfully destroyed.' } }
      format.json { render json: {"data" => []}}
    end
  end

  def show_comments
    respond_to do |format|
      format.js
    end
  end

  def view_assigned_visits
     @events_array = []
     @today_visits = []
     @visits = Visit.user_visits(current_user.id)
     @visits.each do |visit|
       @events_array << { title: "#{visit.visit_type.title} ##{visit.id}",
                          start: visit.time_in.strftime('%Y, %m, %d'),
                          end: visit.time_out.strftime('%Y, %m, %d')}
       @today_visits << visit if visit.date && visit.date.today?
     end

  end

  def scrape_visits
    authorize! :edit, Visit
    msg = 'Scrapping visits is in progress'
    type = :success
    begin
      Visit.delay.scrape_visits
    rescue e
      msg = "Scrapping visits success#{}"
      type = :error
    end
    redirect_to visits_path, flash: { type => msg }
  end

  private

  def set_reimbursements
    not_included_reimbursements = @visit.visit_type.reimbursements - @visit.reimbursements
    @new_reimbursements_visits = []
    not_included_reimbursements.each do |reimbursement|
      @new_reimbursements_visits << reimbursement.reimbursements_visits.new
      @new_reimbursements_visits.last.visit = @visit
    end
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_visit
    @visit = Visit.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def visit_params
    params.require(:visit).permit(
      :notification,
      :medical_record_number, 
      :progress_state, 
      :billing_state, 
      :billing_code, 
      :date, 
      :assigned_time, 
      :occurred_time, 
      :agency_id, 
      :assigner_id, 
      :assignee_id, 
      :patient_id, 
      :visit_type_id, 
      :time_in,
      :time_out,
      reimbursements_visits_attributes: [:reimbursement_id, :id, :action_count, :comment, :_destroy]
      )
  end
end

app/views/visits/_comments.html.haml
.modal-dialog
  .modal-content
    .modal-header
      %button.close{"aria-hidden" => "true", "data-dismiss" => "modal", :type => "button"} ×
      %h4#simpleModalLabel.modal-title Reimbursements
    .modal-body
      = render partial: 'comments/comments', locals: {commentable: @visit}
      .clearfix
      = render partial: 'comments/form', locals: {commentable: @visit}

app/views/visits/_form.html.haml
= form_for @visit do |f|
  .card
    .card-body
      .row
        .col-md-6
          %table.table-no-border
            %tr
              %td.table-right-col
                - if @visit.errors.any?
                  #error_explanation
                    .alert.alert-callout.alert-info.no-margin
                      %h2= "#{pluralize(@visit.errors.count, "error")} prohibited this form from being saved:"
                      %ul
                        - @visit.errors.full_messages.each do |msg|
                          %li= msg
        .row
          .col-md-12
            .form-horizontal
              .form-group
                = f.label :visit_type, class: "col-sm-1 control-label"
                .col-sm-11
                  = f.select :visit_type_id, options_from_collection_for_select(VisitType.all, :id, :title, @visit.visit_type_id), {:include_blank => true}, {class: "form-control", onchange: 'get_dependant_data(this)'}
                  .form-control-line
              .form-group
                = f.label :date, class: "col-sm-1 control-label"
                .col-sm-11#date.input-group.date
                  = f.text_field :date, class: 'datepicker form-control'
                  .form-control-line
              .form-group
                = f.label :assigned_time, class: "col-sm-1 control-label"
                .col-sm-11.mini_datetime_select
                  = f.datetime_select :assigned_time, class: 'form-control'
                  .form-control-line
              .form-group
                = f.label :occurred_time, class: "col-sm-1 control-label"
                .col-sm-11.mini_datetime_select
                  = f.datetime_select :occurred_time, class: 'form-control'
                  .form-control-line
              .form-group
                = f.label :time_in, class: "col-sm-1 control-label"
                .col-sm-11.mini_datetime_select
                  = f.text_field :time_in, class: 'form-control', type: 'time', value: @visit.time_in.try(:to_time).try(:strftime, "%H:%M")
                  .form-control-line
              .form-group
                = f.label :time_out, class: "col-sm-1 control-label"
                .col-sm-11.mini_datetime_select
                  = f.text_field :time_out, class: 'form-control', type: 'time', value: @visit.time_out.try(:to_time).try(:strftime, "%H:%M")
                  .form-control-line
              .form-group
                = f.label :agency_id, class: "col-sm-1 control-label"
                .col-sm-11
                  = f.select :agency_id, options_from_collection_for_select(Agency.all, :id, :display_name, @visit.assigner_id), {:include_blank => true}, {class: "form-control"}
                  .form-control-line
              .form-group
                = f.label :assignee_id, class: "col-sm-1 control-label"
                .col-sm-11
                  = f.select :assignee_id, options_from_collection_for_select(User.all, :id, :display_name, @visit.assignee_id), {:include_blank => true}, {class: "form-control"}
                  .form-control-line
              .form-group
                = f.label :patient_id, class: "col-sm-1 control-label"
                .col-sm-11
                  = f.select :patient_id, options_from_collection_for_select(Patient.all, :id, :display_name, @visit.patient_id), {:include_blank => true}, {class: "form-control"}
                  .form-control-line
  
  - content_for :footer do
    = section_submit_action "Submit", f.options[:html][:id]
    = section_action "reply", scrape_visits_path, "Visits"
/ :javascript 
/   function get_dependant_data(selectElm){
/     $.ajax({
/       url: "#{get_visit_type_dependant_data_path}",

/       type: "GET",
/       data: {id:  selectElm.value}
/     })
/   }

app/views/visits/_modal_form.html.haml
.modal-dialog
  .modal-content
    .modal-header
      %button.close{"aria-hidden" => "true", "data-dismiss" => "modal", :type => "button"} ×
      %h4#simpleModalLabel.modal-title Reimbursements
    .modal-body
      = form_for @visit, remote:true  do |f|
        = hidden_field_tag :timesheet_id , @timesheet_id if @timesheet_id
        - if @visit.errors.any?
          #error_explanation
            .alert.alert-callout.alert-info.no-margin
              %h2= "#{pluralize(@visit.errors.count, "error")} prohibited this form from being saved:"
              %ul
                - @visit.errors.full_messages.each do |msg|
                  %li= msg
        .form-horizontal
          .form-group
            = f.label :time_in, class: "col-sm-2 control-label"
            .col-sm-10.mini_datetime_select
              = f.datetime_select :time_in, class: 'form-control'
              .form-control-line
          .form-group
            = f.label :time_out, class: "col-sm-2 control-label"
            .col-sm-10.mini_datetime_select
              = f.datetime_select :time_out, class: 'form-control'
              .form-control-line


        %table.table-no-border
          %tr
            %td.table-right-col
              - if @visit.errors.any?
                #error_explanation
                  .alert.alert-callout.alert-info.no-margin
                    %h2= "#{pluralize(@visit.errors.count, "error")} prohibited this form from being saved:"
                    %ul
                      - @visit.errors.full_messages.each do |msg|
                        %li= msg
          %table.table.table-hover
            %thead
              %tr
                %th.text-md Title
                %th.text-md Price
                %th.text-md Action Count
                %th.text-md Comment
            = f.fields_for :reimbursements_visits, @visit.reimbursements_visits do |builder|
              %tr
                %td
                  = builder.object.reimbursement.title
                %td
                  = builder.object.reimbursement.riembursement_price(@visit.assignee)
                %td.action-count-field
                  - if builder.object.reimbursement.value_type == 1
                    %label
                      = check_box_tag :remove_field, nil, @visit.reimbursement_ids.include?(builder.object.reimbursement.id) ? true : false , { onchange: 'count_switcher(this)'}
                      = builder.hidden_field :action_count, {class: 'action-count-field'}
                      = builder.hidden_field :_destroy, {class: 'destroy-field', value: false}
                  - else
                    = builder.number_field :action_count, class: "form-control multiple-instances", min: 0, :step => 1, onchange: "counter_listener(this)"
                    = builder.hidden_field :_destroy, {class: 'destroy-field', value: false}
                %td
                  = builder.text_field :comment, {class: "form-control"}
            = f.fields_for :reimbursements_visits, @new_reimbursements_visits do |builder|
              = builder.hidden_field :reimbursement_id
              %tr
                %td
                  = builder.object.reimbursement.title
                %td
                  = builder.object.reimbursement.riembursement_price(@visit.assignee)
                %td.action-count-field
                  - if builder.object.reimbursement.value_type == 1
                    %label
                      = check_box_tag :remove_field, nil, @visit.reimbursement_ids.include?(builder.object.reimbursement.id) ? true : false , { onchange: 'count_switcher(this)'}
                      = builder.hidden_field :action_count, {class: 'action-count-field', value: 0}
                      = builder.hidden_field :_destroy, {class: 'destroy-field', value: true}
                  - else
                    = builder.number_field :action_count, class: "form-control multiple-instances", min: 0, :step => 1, value: 0, onchange: "counter_listener(this)"
                    = builder.hidden_field :_destroy, {class: 'destroy-field', value: true}
                %td
                  = builder.text_field :comment, {class: "form-control"}
        .modal-footer
          %button.btn.btn-default{"data-dismiss" => "modal", :type => "button"} Cancel
          = f.submit "Save", class: 'btn btn-primary'
    .modal-header
      %button.close{"aria-hidden" => "true", "data-dismiss" => "modal", :type => "button"} ×
      %h4#simpleModalLabel.modal-title Comments
    .modal-body
      = render partial: 'comments/comments', locals: {commentable: @visit}
      .clearfix
      = render partial: 'comments/form', locals: {commentable: @visit}


/ :javascript 
/   function get_dependant_data(selectElm){
/     $.ajax({
/       url: "#{get_visit_type_dependant_data_path}",

/       type: "GET",
/       data: {id:  selectElm.value}
/     })
/   }

:javascript

app/views/visits/_reimbursements.html.haml
= form_for visit , :class => "edit-visit" do |f|
  %table.table-no-border
    %tr
      %td.table-right-col
        - if visit.errors.any?
          #error_explanation
            .alert.alert-callout.alert-info.no-margin
              %h2= "#{pluralize(visit.errors.count, "error")} prohibited this form from being saved:"
              %ul
                - visit.errors.full_messages.each do |msg|
                  %li= msg
  %table.table.text-xs
    %thead
      %tr
        %th.col-md-4 Title
        %th.col-md-2 Request
        %th.col-nd-6 Comment
    = f.fields_for :reimbursements_visits, visit.reimbursements_visits do |builder|
      %tr
        %td
          = builder.object.reimbursement.title

        %td.action-count-field
          - if builder.object.reimbursement.value_type == 1
            = builder.check_box :action_count,  { "class": "single_instance input-xs", "data-rid": builder.object.id, "disabled": true }
          - else
            = builder.number_field :action_count, {"data-rid": builder.object.id, "data-count": builder.object.action_count, "class": "form-control multiple-instance input-sm text-left", min: 0, step: 1, "disabled": true}
        %td
          = builder.text_field :comment, {class: "form-control", "disabled": true}

app/views/visits/edit.html.haml
.section-body
  .card
    .card-head.style-primary
      %header.text-xl
        Editing visit

  = render 'form'

app/views/visits/edit.js.haml
$("#visit_modal").html("#{escape_javascript(render('modal_form')).html_safe}");
$("#visit_modal").modal('show');





var time1 = $($("#visit_modal  .mini_datetime_select")[0]);
var time2 = $($("#visit_modal  .mini_datetime_select")[1]);

$(time1.find("select")[0]).hide();
$(time1.find("select")[1]).hide();
$(time1.find("select")[2]).hide();


$(time2.find("select")[0]).hide();
$(time2.find("select")[1]).hide();
$(time2.find("select")[2]).hide();
$("input[type='hidden']+span").remove();

app/views/visits/index.html.haml
.section-body
  .card.card-underline
    .card-body
      .table-responsive
        %table.table.table-hover.people-table#visits-datatable{"data-source" => visits_path(format: :json)}
          %thead
            %tr
              %th Progress state
              %th Billing state
              %th Billing code
              %th Date
              %th Time in
              %th Time out
              %th Agency
              %th Patient
              %th Visit type
              %th Assignee
              %th Controls

  - content_for :header_title do 
    Visits

  - content_for :footer do
    - if can? :edit, Visit
      = section_floating_action "plus", new_visit_path, "New visit"
    - if current_user.admin?
      = section_action "refresh", scrape_visits_path, "Visits"  
  
:javascript
  $(function () {
    $('#visits-datatable').DataTable(
    {
      "processing": true,
      "serverSide": true,
      "ajax": $('#visits-datatable').data('source'),
      "dom": 'lCfrtip',
      "order": [[ 0, "asc" ]],
      "colVis": {
        "buttonText": "Columns",
        "overlayFade": 0,
        "align": "right"
      },
      "columnDefs": [
        { className: "people-info", "targets": [ 0 ],
          "orderable": false, "targets": [ 10 ]}
      ],
      "language": {
        "lengthMenu": '_MENU_ entries per page',
        "search": '<i class="fa fa-search"></i>',
        "paginate": {
          "previous": '<i class="fa fa-angle-left"></i>',
          "next": '<i class="fa fa-angle-right"></i>'
        }
      }
    });
  });

app/views/visits/new.html.haml
.section-body
 
  = render 'form'

- content_for :header_title do 
  New visit

app/views/visits/show_comments.js.haml
$("#visit_modal").html("#{escape_javascript(render('comments')).html_safe}");
$("#visit_modal").modal('show');

app/views/visits/update.js.haml
$("#visit_modal").modal('hide');
/ window.location.reload()