config/routes.rb
Rails.application.routes.draw do

  get 'templates/floating_menu'

  get 'billing_reports/payments' => 'billing_reports#payments', as: 'payments_datatable'
  get 'billing_reports/payments_summary' => 'billing_reports#payments_summary', as: 'payments_summary'
  get 'billing_reports/weekly_bills_summary'
  get 'billing_reports/receivables_summary'
  get 'bills/index_report_bills'
  get 'fetch_bill_paid_amount' => 'bills#fetch_bill_paid_amount', as: 'fetch_bill_paid_amount'

  resources :bonuses
  resources :payments
  resources :on_calls do
    resources :comments
  end
  resources :claim_types
  resources :payment_types
  resources :availabilities
  resources :insurance_companies
  resources :reimbursement_timesheets do
    resources :comments
  end

  get 'bills/delete_all_bills' => 'bills#delete_all_bills'
  resources :bills do
    resources :payments
    collection do
      post :import
      get :reports
      get :receivables
    end
  end

  resources :reports do
    member do
      get :generate_instance
      get :export
    end
    collection do
      get :get_form_fields
      get :get_field_aliases
      get :get_field_basic_types
    end
  end

  resources :notifications, only: [:index] do
    collection do
      post :mark_all_as_read
      get :mark_as_read
    end
  end

  resources :hour_types
  resources :hours do
    resources :comments
  end

  get 'show_patients_forms' => 'admin_patients#show_patients_forms', as: 'show_patients_forms'
  
  resources :admin_configurations, only: [:index, :update]

  namespace :admin do
    get :users
    put :update_users_roles_permissions
    get :patients
    put :update_patients_roles_permissions
    put :timesheets
    put :update_timesheets_roles_permissions
    get :visits
    put :update_visits_roles_permissions
    get :bills
    put :update_bills_roles_permissions
  end

  resources :coverage_areas

  resources :agencies

  resources :visits do
    resources :comments
    get :add_reimbursement
  end

  resources :visit_types

  resources :reimbursements

  resources :diseases

  resources :departments

  get 'reports/get_total_report'

  get 'create_timesheet' => "timesheets#create_timesheet", as: 'create_timesheet'

  mount CustomForms::Engine => '/'

  get 'timesheets/update_task_state', as: 'update_task_state'

  get 'timesheets/latest' => 'timesheets#show_latest', as: 'latest_timesheet'
  get 'employees_timesheets' => 'timesheets#employees_timesheets', as: 'employees_timesheets'
  
  resources :timesheets, only: [:index, :show, :update] do
    resources :comments
    member do
      put :submit
      put :admit
      put :pay
      get :send_email_to_owner
    end
  end
  put 'timesheets' => 'timesheets#index' 
  resources :payrolls do 
    member do
      get 'payroll_statistics/get_exceeded_employees', as: 'get_exceeded_employees'
      get 'payroll_statistics/show_employees_visits_per_patient', as: 'show_employees_visits_per_patient'
      get 'payroll_statistics/show_top_ten_employees', as: 'show_top_ten_employees'
      get 'payroll_statistics/show_employees_with_reimb', as: 'show_employees_with_reimb'
      get 'payroll_statistics/show_employees_with_over_time', as: 'show_employees_with_over_time'
      
    end
  end

  resources :roles

  resources :user_documents

  resources :document_types

  get 'admin/index'

  resources :license_types

  resources :job_types

  get "find_patients_matches" => "patients#find_patients_matches", as: "find_patients_matches"
  get 'patients/delete_all_patients' => 'patients#delete_all_patients', as: "delete_all_patients"
  resources :patients do
    put :update_forms, on: :member
    get :get_patient_data
  end

  get 'scrape_users' => 'users#scrape_users'
  get 'scrape_agencies' => 'agencies#scrape_agencies'
  get 'scrape_patients' => 'patients#scrape_patients'
  get 'scrape_visits' => 'visits#scrape_visits'

  root 'users#index'
  devise_for :users, controllers: { registrations: 'users' }
  resources :users, except: :destroy do
    put :update_forms, on: :member
    post :reset_password_via_email
    resources :timesheets, only: [:index, :show, :update] do
      member do
        put :submit
        put :admit
        put :pay
      end
    end
    member do
      post :deactivate_user
      post :activate_user
      put :update_password
    end
    resources :visits
  end

  get 'edit_roles' => 'users#edit_user_roles', as: 'edit_user_roles'
  put 'update_user_role' => 'users#update_user_role', as: 'update_user_role'

  get 'view_assigned_visits' => 'visits#view_assigned_visits', as: 'view_assigned_visits'
  get 'get_visit_type_dependant_data' => 'visit_types#get_visit_type_dependant_data', as: 'get_visit_type_dependant_data'

  get 'static_page/:page' => 'static#show'
  get 'show_comments' => 'visits#show_comments'

end

app/views/timesheets/show/submitted/admittor/_activities.html.haml
/ = render "timesheets/show/shared/billsheet",visits: @pending_visits, hours: (@pending_hours)

= form_tag(update_task_state_path, method: :get, remote:true, id: "update_task") do 
  = hidden_field_tag :id, @timesheet.id
  = hidden_field_tag :state, 'visited'
  = hidden_field_tag :task_type, 'visit'
  - if visits 
    - visits.each do |v|
      = check_box_tag 'task_id[]',  v.id, false, class: "hidden" if submittable?(@timesheet)

.col-md-12
  - if visits
    = render "timesheets/show/submitted/admittor/visits", visits: visits
 
  - if hours
    = render 'timesheets/show/submitted/admittor/hours', hours: hours

  - if on_calls_line_items
    = render "timesheets/show/submitted/admittor/on_call", on_calls_line_items: on_calls_line_items


  - if reimbursement_timesheets_line_items
    = render "timesheets/show/submitted/admittor/reimbursements", reimbursement_timesheets_line_items: reimbursement_timesheets_line_items

  = render "timesheets/bonus"


#hour_modal.modal.fade{"aria-hidden" => "true", "aria-labelledby" => "simpleModalLabel", :role => "dialog", :tabindex => "-1"}
  .modal-dialog
    .modal-content
      .modal-header
        %button.close{"aria-hidden" => "true", "data-dismiss" => "modal", :type => "button"} ×
        %h4#simpleModalLabel.modal-title Save changes
      .modal-body
        %p Do you want to save changes?
      .modal-footer
        %button.btn.btn-default{"data-dismiss" => "modal", :type => "button"} Cancel
        %button.btn.btn-primary{:type => "button"} Save changes



#on_call_modal.modal.fade{"aria-hidden" => "true", "aria-labelledby" => "simpleModalLabel", :role => "dialog", :tabindex => "-1"}
  .modal-dialog
    .modal-content
      .modal-header
        %button.close{"aria-hidden" => "true", "data-dismiss" => "modal", :type => "button"} ×
        %h4#simpleModalLabel.modal-title Save changes
      .modal-body
        %p Do you want to save changes?
      .modal-footer
        %button.btn.btn-default{"data-dismiss" => "modal", :type => "button"} Cancel
        %button.btn.btn-primary{:type => "button"} Save changes
        
#reimbursement_timesheet_modal.modal.fade{"aria-hidden" => "true", "aria-labelledby" => "simpleModalLabel", :role => "dialog", :tabindex => "-1"}
  .modal-dialog
    .modal-content
      .modal-header
        %button.close{"aria-hidden" => "true", "data-dismiss" => "modal", :type => "button"} ×
        %h4#simpleModalLabel.modal-title Save changes
      .modal-body
        %p Do you want to save changes?
      .modal-footer
        %button.btn.btn-default{"data-dismiss" => "modal", :type => "button"} Cancel
        %button.btn.btn-primary{:type => "button"} Save changes

#bonus_modal.modal.fade{"aria-hidden" => "true", "aria-labelledby" => "simpleModalLabel", :role => "dialog", :tabindex => "-1"}

:javascript
  $(document).ready(function() {
    setup_visit_events();
    setup_card_collapse(); 
    $('#unbilled-visits-datatable').DataTable();
  });

app/views/timesheets/show/submitted/admittor/_hour_row.html.haml
%td= state_badge hour.progress_state
%td= date hour.date
%td= time hour.from
%td= time hour.to
%td= distance_of_time_in_words(hour.from, hour.to)
%td= hour.try(:comments).try(:first).try(:content)
%td.text-right
  - if hour.progress_state == "pending"
    %a.btn.btn-xs.text-success{href: update_task_state_path(id: @timesheet.id, task_id: [hour.id], state: 'approved', user_id: @timesheet.user.id, task_type: 'hour'), "data-remote": true}
      %i.fa.fa-check

    %a.btn.btn-xs.text-danger{href: update_task_state_path(id: @timesheet.id, task_id: [hour.id], state: 'rejected', user_id: @timesheet.user.id, task_type: 'hour'), "data-remote": true}
      %i.fa.fa-times

  - else
    %a.btn.btn-xs.text-danger{href: update_task_state_path(id: @timesheet.id, task_id: [hour.id], state: 'pending', user_id: @timesheet.user.id, task_type: 'hour'), "data-remote": true}
      %i.fa.fa-minus-circle

  %a.btn.btn-xs.ink-reaction.text-primary{class: ("pulse1" unless hour.comments.empty?), href: "#offcanvas-hour-#{hour.id}-comments" , "data-toggle": "offcanvas", "data-backdrop": "false"}
    %i.fa.fa-comment

app/views/timesheets/show/submitted/admittor/_hours.html.haml
.card
  .card-underline
    .card-head
      %header.text-lg
        Hours
      - if @timesheet.user == current_user and @timesheet.state == "created"
        .tools
          = link_to new_hour_path(user_id: current_user.id, timesheet_id: @timesheet.id, progress_state: 'pending') , class: 'pull-right btn btn-floating-action ink-reaction btn-info btn-xs', "data-remote":"true" do 
            %i.fa.fa-plus
    
    .card-body#hours_table.text-xs
      - unless hours.empty?
        %table#unbilled-hours-datatable.table.table-condensed{"cellspacing":"0"}
          %thead 
            %tr
              %th.col-md-1 State
              %th.col-md-2 Date
              %th.col-md-1 Time in
              %th.col-md-1 Time out
              %th.col-md-2 Total time
              %th.col-md-5 Notes
              %th.text-right Actions
              
          %tbody
            - hours.each do |hour|
              %tr
                = render "timesheets/show/submitted/admittor/hour_row", hour: hour

      - else
        Click (+) to log Hours to this timesheet

app/views/timesheets/show/submitted/admittor/_on_call.html.haml
.card.card-underline
  .card-head
    %header.text-lg
      On Call
    - if @timesheet.user == current_user and @timesheet.state == "created"
      .tools
        = link_to new_on_call_path(user_id: current_user.id, timesheet_id: @timesheet.id, progress_state: 'pending') , class: 'pull-right btn btn-floating-action ink-reaction btn-info btn-xs', "data-remote":"true" do 
          %i.fa.fa-plus
  .card-body#on_call_table.text-xs
    - if on_calls_line_items and !on_calls_line_items.empty?
      %table#unbilled-visits-datatable.table.table-condensed{"cellspacing":"0"}
        %thead 
          %tr
            %th.col-md-1 State
            %th.col-md-2 Date
            %th.col-md-6 Notes
            %th.col-md-1.text-right Actions
        %tbody
          - on_calls_line_items.map(&:payable).each do |on_call|
            %tr
              = render "timesheets/show/submitted/admittor/on_call_row", on_call: on_call
    - else
      Click (+) to log On Call entries to this timesheet

app/views/timesheets/show/submitted/admittor/_on_call_row.html.haml
%td= state_badge on_call.progress_state
%td= on_call.date.strftime("%e, %b, %y")
%td= on_call.note
%td.text-right
  - if on_call.progress_state == "pending"
    %a.btn.btn-xs.text-success{href: update_task_state_path(id: @timesheet.id, task_id: [on_call.id], state: 'approved', user_id: @timesheet.user.id, task_type: 'on_call'), "data-remote": true}
      %i.fa.fa-check
    %a.btn.btn-xs.text-danger{href: update_task_state_path(id: @timesheet.id, task_id: [on_call.id], state: 'rejected', user_id: @timesheet.user.id, task_type: 'on_call'), "data-remote": true}
      %i.fa.fa-times
  - else
    %a.btn.btn-xs.text-danger{href: update_task_state_path(id: @timesheet.id, task_id: [on_call.id], state: 'pending', user_id: @timesheet.user.id, task_type: 'on_call'), "data-remote": true}
      %i.fa.fa-minus-circle
  %a.btn.btn-xs.ink-reaction.text-primary{class: ("pulse1" unless on_call.comments.empty?), href: "#offcanvas-oncall-#{on_call.id}-comments" , "data-toggle": "offcanvas", "data-backdrop": "false"}
    %i.fa.fa-comment

app/views/timesheets/show/submitted/admittor/_reimbursement.html.haml
.input-group
  - rs = v.reimbursements_visits.sort_by { |v| v.reimbursement.id }
  - rs.each do |r|
    .row
      - if r.action_count > 0
        
        %span.input-group-addon.text-xs
          - if r.reimbursement.value_type == 1
            = r.reimbursement.title
          - else
            = "#{r.reimbursement.title} x#{r.action_count}"
        .input-group-content
          = r.comment             

app/views/timesheets/show/submitted/admittor/_reimbursement_row.html.haml
%td= state_badge reimb.progress_state
%td= date reimb.created_at
%td= reimbursement_title reimb
%td= StringFormatter.format_currency((reimb.action_count || 1).to_f * reimb.reimbursement.riembursement_price.to_f)
%td= reimb.note
%td.text-right
  - if reimb.progress_state == "pending"
    %a.btn.btn-xs.text-success{href: update_task_state_path(id: @timesheet.id, task_id: [reimb.id], state: 'approved', user_id: @timesheet.user.id, task_type: 'reimbursement_timesheet'), "data-remote": true}
      %i.fa.fa-check
    %a.btn.btn-xs.text-danger{href: update_task_state_path(id: @timesheet.id, task_id: [reimb.id], state: 'rejected', user_id: @timesheet.user.id, task_type: 'reimbursement_timesheet'), "data-remote": true}
      %i.fa.fa-times
  - else
    %a.btn.btn-xs.text-danger{href: update_task_state_path(id: @timesheet.id, task_id: [reimb.id], state: 'pending', user_id: @timesheet.user.id, task_type: 'reimbursement_timesheet'), "data-remote": true}
      %i.fa.fa-minus-circle


  %a.btn.btn-xs.ink-reaction.text-primary{class: ("pulse1" unless reimb.comments.empty?), href: "#offcanvas-reimb-#{reimb.id}-comments" , "data-toggle": "offcanvas", "data-backdrop": "false"}
    %i.fa.fa-comment

app/views/timesheets/show/submitted/admittor/_reimbursements.html.haml
.card.card-underline
  .card-head
    %header.text-lg
      Reimbursements
    - if @timesheet.user == current_user and @timesheet.state == "created"
      .tools
        = link_to new_reimbursement_timesheet_path(user_id: current_user.id, timesheet_id: @timesheet.id, progress_state: 'pending') , class: 'pull-right btn btn-floating-action ink-reaction btn-info btn-xs', "data-remote":"true" do 
          %i.fa.fa-plus

  .card-body#reimbursement_timesheet_table.text-xs
    - if reimbursement_timesheets_line_items and !reimbursement_timesheets_line_items.empty?
      %table.table.table-condensed{"cellspacing":"0"}
        %thead 
          %tr
            %th.col-md-1 State
            %th.col-md-2 Date
            %th.col-md-2 Reimbursement
            %th.col-md-6 Amount
            %th.col-md-6 Notes
            %th.col-md-1.text-right Actions
            
        %tbody
          - reimbursement_timesheets_line_items.map(&:payable).each do |reimb|
            %tr
              = render "timesheets/show/submitted/admittor/reimbursement_row", reimb: reimb
    - else
      Click (+) to add Reimbursements to this timesheet

   

app/views/timesheets/show/submitted/admittor/_visit_row.html.haml
- visit = "Visit ##{v.id}"
- if v.visit_type and v.visit_type.title
  - visit = "#{v.visit_type.title} ##{v.id}"    
%td.text-center
  = state_badge v.progress_state

%td.trunc-hover-show
  = v.patient.try(:display_name)
%td.trunc-hover-show
  = visit
  /= render_visit_state(@timesheet, v)
%td= visit_time v
%td
  = render "timesheets/show/submitted/admittor/reimbursement", v: v
%td.text-right
  %form.inline-form.table-inline-form
    .input-group
      .btn-xs-group
        %a.btn.btn-xs.ink-reaction.text-primary{class: ("pulse1" unless v.comments.empty?), href: "#offcanvas-visit-#{v.id}-comments" , "data-toggle": "offcanvas", "data-backdrop": "false"}
          %i.fa.fa-comment
        %a.btn.btn-xs.text-primary{href: "#{visit_path(v)}", target: "_blank" }
          %i.fa.fa-eye
        - if v.progress_state == "pending"
          %a.btn.btn-xs.text-success{href: update_task_state_path(id: @timesheet.id, task_id: [v.id], state: 'approved', user_id: @timesheet.user.id,), "data-remote": true}
            %i.fa.fa-check
          %a.btn.btn-xs.text-danger{href: update_task_state_path(id: @timesheet.id, task_id: [v.id], state: 'rejected', user_id: @timesheet.user.id, task_type: 'visit'), "data-remote": true}
            %i.fa.fa-times
        - else
          %a.btn.btn-xs.text-danger{href: update_task_state_path(id: @timesheet.id, task_id: [v.id], state: 'pending', user_id: @timesheet.user.id), "data-remote": true}
            %i.fa.fa-minus-circle
          
      
      
        

app/views/timesheets/show/submitted/admittor/_visits.html.haml
.card.card-underline
  .card-head
    %header.text-lg
      Visits
    - if @timesheet.user == current_user and @timesheet.state == "created"
      .tools
        %a.pull-right.btn.btn-floating-action.ink-reaction.btn-info.btn-xs{href: "#offcanvas-visits" , "data-toggle": "offcanvas", "data-backdrop": "false"}
          %i.fa.fa-plus
  .card-body#visits_table
    - unless visits and visits.empty?
      %table#unbilled-visits-datatable.table.table-condensed.text-xs{"cellspacing":"0"}
        %thead 
          %tr
            %th.text-sm State
            %th.col-md-2.text-sm Patient
            %th.col-md-2.text-sm Visit
            %th.col-md-2.text-sm Date [Timein - Timeout]
            %th.col-md-5.text-sm Reimbursements
            %th.col-md-1.text-sm Actions


        %tbody
          - visits.each do |v|
            - if v.reimbursements_visits.try(:any?)
              %tr
                = render partial: "timesheets/show/submitted/admittor/visit_row", locals: { v: v }
    - else
      %span Click (+) to add visits to this timesheet