config/routes.rb
Rails.application.routes.draw do

  get 'templates/floating_menu'

  get 'billing_reports/payments' => 'billing_reports#payments', as: 'payments_datatable'
  get 'billing_reports/payments_summary' => 'billing_reports#payments_summary', as: 'payments_summary'
  get 'billing_reports/weekly_bills_summary'
  get 'billing_reports/receivables_summary'
  get 'bills/index_report_bills'
  get 'fetch_bill_paid_amount' => 'bills#fetch_bill_paid_amount', as: 'fetch_bill_paid_amount'

  resources :bonuses
  resources :payments
  resources :on_calls do
    resources :comments
  end
  resources :claim_types
  resources :payment_types
  resources :availabilities
  resources :insurance_companies
  resources :reimbursement_timesheets do
    resources :comments
  end

  get 'bills/delete_all_bills' => 'bills#delete_all_bills'
  resources :bills do
    resources :payments
    collection do
      post :import
      get :reports
      get :receivables
    end
  end

  resources :reports do
    member do
      get :generate_instance
      get :export
    end
    collection do
      get :get_form_fields
      get :get_field_aliases
      get :get_field_basic_types
    end
  end

  resources :notifications, only: [:index] do
    collection do
      post :mark_all_as_read
      get :mark_as_read
    end
  end

  resources :hour_types
  resources :hours do
    resources :comments
  end

  get 'show_patients_forms' => 'admin_patients#show_patients_forms', as: 'show_patients_forms'
  
  resources :admin_configurations, only: [:index, :update]

  namespace :admin do
    get :users
    put :update_users_roles_permissions
    get :patients
    put :update_patients_roles_permissions
    put :timesheets
    put :update_timesheets_roles_permissions
    get :visits
    put :update_visits_roles_permissions
    get :bills
    put :update_bills_roles_permissions
  end

  resources :coverage_areas

  resources :agencies

  resources :visits do
    resources :comments
    get :add_reimbursement
  end

  resources :visit_types

  resources :reimbursements

  resources :diseases

  resources :departments

  get 'reports/get_total_report'

  get 'create_timesheet' => "timesheets#create_timesheet", as: 'create_timesheet'

  mount CustomForms::Engine => '/'

  get 'timesheets/update_task_state', as: 'update_task_state'

  get 'timesheets/latest' => 'timesheets#show_latest', as: 'latest_timesheet'
  get 'employees_timesheets' => 'timesheets#employees_timesheets', as: 'employees_timesheets'
  
  resources :timesheets, only: [:index, :show, :update] do
    resources :comments
    member do
      put :submit
      put :admit
      put :pay
      get :send_email_to_owner
    end
  end
  put 'timesheets' => 'timesheets#index' 
  resources :payrolls do 
    member do
      get 'payroll_statistics/get_exceeded_employees', as: 'get_exceeded_employees'
      get 'payroll_statistics/show_employees_visits_per_patient', as: 'show_employees_visits_per_patient'
      get 'payroll_statistics/show_top_ten_employees', as: 'show_top_ten_employees'
      get 'payroll_statistics/show_employees_with_reimb', as: 'show_employees_with_reimb'
      get 'payroll_statistics/show_employees_with_over_time', as: 'show_employees_with_over_time'
      
    end
  end

  resources :roles

  resources :user_documents

  resources :document_types

  get 'admin/index'

  resources :license_types

  resources :job_types

  get "find_patients_matches" => "patients#find_patients_matches", as: "find_patients_matches"
  get 'patients/delete_all_patients' => 'patients#delete_all_patients', as: "delete_all_patients"
  resources :patients do
    put :update_forms, on: :member
    get :get_patient_data
  end

  get 'scrape_users' => 'users#scrape_users'
  get 'scrape_agencies' => 'agencies#scrape_agencies'
  get 'scrape_patients' => 'patients#scrape_patients'
  get 'scrape_visits' => 'visits#scrape_visits'

  root 'users#index'
  devise_for :users, controllers: { registrations: 'users' }
  resources :users, except: :destroy do
    put :update_forms, on: :member
    post :reset_password_via_email
    resources :timesheets, only: [:index, :show, :update] do
      member do
        put :submit
        put :admit
        put :pay
      end
    end
    member do
      post :deactivate_user
      post :activate_user
      put :update_password
    end
    resources :visits
  end

  get 'edit_roles' => 'users#edit_user_roles', as: 'edit_user_roles'
  put 'update_user_role' => 'users#update_user_role', as: 'update_user_role'

  get 'view_assigned_visits' => 'visits#view_assigned_visits', as: 'view_assigned_visits'
  get 'get_visit_type_dependant_data' => 'visit_types#get_visit_type_dependant_data', as: 'get_visit_type_dependant_data'

  get 'static_page/:page' => 'static#show'
  get 'show_comments' => 'visits#show_comments'

end

app/controllers/bonuses_controller.rb
class BonusesController < ApplicationController
  before_action :set_bonuse, only: [:show, :edit, :update, :destroy]

  # GET /bonuses
  # GET /bonuses.json
  def index
    @bonuses = Bonuse.all
  end

  # GET /bonuses/1
  # GET /bonuses/1.json
  def show
  end

  # GET /bonuses/new
  def new
    @bonuse = Bonuse.new
    user = User.find(params[:user_id])
    @bonuse = Bonuse.new(user_id: user.id, timesheet_id: params[:timesheet_id])
    @timesheet_id = params[:timesheet_id] || nil
    respond_to do |format|
      format.html
      format.js
    end
  end

  # GET /bonuses/1/edit
  def edit
  end

  # POST /bonuses
  # POST /bonuses.json
  def create
    @bonuse = Bonuse.new(bonuse_params)
    respond_to do |format|
      if @bonuse.save
        if params[:timesheet_id]
          format.html { redirect_to @bonuse, notice: 'Bonuse was successfully created.' }
          format.json { render :show, status: :created, location: @bonuse }
          format.js {redirect_to timesheet_path(id: params[:timesheet_id], user_id: @bonuse.user.id)}
        end
      else
        format.html { render :new }
        format.json { render json: @bonuse.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bonuses/1
  # PATCH/PUT /bonuses/1.json
  def update
    respond_to do |format|
      if @bonuse.update(bonuse_params)
        format.html { redirect_to @bonuse, notice: 'Bonuse was successfully updated.' }
        format.json { render :show, status: :ok, location: @bonuse }
      else
        format.html { render :edit }
        format.json { render json: @bonuse.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bonuses/1
  # DELETE /bonuses/1.json
  def destroy
    @bonuse.destroy
    respond_to do |format|
      format.html { redirect_to bonuses_url, notice: 'Bonuse was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bonuse
      @bonuse = Bonuse.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bonuse_params
      params.require(:bonuse).permit(:user_id, :price, :timesheet_id)
    end
end

app/helpers/bonuses_helper.rb
module BonusesHelper
end

app/views/bonuses/_errors.html.haml
- if @bonuse.errors.any?
  .alert.alert-callout.alert-danger.no-margin
    %p= "#{pluralize(@bonuse.errors.count, "error")} prohibited this form from being saved:"
    %ul
      - errors.full_messages.each do |msg|
        %li.text-xs= msg

app/views/bonuses/_form.html.haml
= form_for @bonuse do |f|
  - if @bonuse.errors.any?
    #error_explanation
      %h2= "#{pluralize(@bonuse.errors.count, "error")} prohibited this bonuse from being saved:"
      %ul
        - @bonuse.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :user_id
    = f.number_field :user_id
  .field
    = f.label :price
    = f.text_field :price
  .field
    = f.label :timesheet_id
    = f.number_field :timesheet_id
  .actions
    = f.submit 'Save'

app/views/bonuses/_modal_form.html.haml
.modal-dialog
  .modal-content
    .modal-header
      %button.close{"aria-hidden" => "true", "data-dismiss" => "modal", :type => "button"} ×
      %h4#simpleModalLabel.modal-title Bonus
    .modal-body
      = form_for @bonuse, remote:true do |f|
        = f.hidden_field :user_id
        = f.hidden_field :timesheet_id
        = hidden_field_tag :timesheet_id , @timesheet_id if @timesheet_id

        = render "bonuses/errors", errors: @bonuse.errors

        .form-horizontal
          .form-group
            = f.label :price, class: "col-sm-2 control-label"
            .col-sm-10
              = f.number_field :price, class: 'form-control numbers_only'
              .form-control-line

        .card-actionbar
          .deactivate-btn.card-title
          = f.submit "Save", class: 'save-form btn btn-info pull-right'

app/views/bonuses/edit.html.haml
%h1 Editing bonuse

= render 'form'

= link_to 'Show', @bonuse
\|
= link_to 'Back', bonuses_path

app/views/bonuses/index.html.haml
%h1 Listing bonuses

%table
  %thead
    %tr
      %th User
      %th Price
      %th Timesheet
      %th
      %th
      %th

  %tbody
    - @bonuses.each do |bonuse|
      %tr
        %td= bonuse.user_id
        %td= bonuse.price
        %td= bonuse.timesheet_id
        %td= link_to 'Show', bonuse
        %td= link_to 'Edit', edit_bonuse_path(bonuse)
        %td= link_to 'Destroy', bonuse, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Bonuse', new_bonuse_path

app/views/bonuses/new.html.haml
%h1 New bonuse

= render 'form'

= link_to 'Back', bonuses_path

app/views/bonuses/new.js.haml
$("#bonus_modal").html("#{escape_javascript(render('modal_form')).html_safe}");
$("#bonus_modal").modal('show');

$('#date input').datetimepicker({format: 'YYYY/MM/DD'});

app/views/bonuses/show.html.haml
%p#notice= notice

%p
  %b User:
  = @bonuse.user_id
%p
  %b Price:
  = @bonuse.price
%p
  %b Timesheet:
  = @bonuse.timesheet_id

= link_to 'Edit', edit_bonuse_path(@bonuse)
\|
= link_to 'Back', bonuses_path