config/routes.rb
Rails.application.routes.draw do

  get 'templates/floating_menu'

  get 'billing_reports/payments' => 'billing_reports#payments', as: 'payments_datatable'
  get 'billing_reports/payments_summary' => 'billing_reports#payments_summary', as: 'payments_summary'
  get 'billing_reports/weekly_bills_summary'
  get 'billing_reports/receivables_summary'
  get 'bills/index_report_bills'
  get 'fetch_bill_paid_amount' => 'bills#fetch_bill_paid_amount', as: 'fetch_bill_paid_amount'

  resources :bonuses
  resources :payments
  resources :on_calls do
    resources :comments
  end
  resources :claim_types
  resources :payment_types
  resources :availabilities
  resources :insurance_companies
  resources :reimbursement_timesheets do
    resources :comments
  end

  get 'bills/delete_all_bills' => 'bills#delete_all_bills'
  resources :bills do
    resources :payments
    collection do
      post :import
      get :reports
      get :receivables
    end
  end

  resources :reports do
    member do
      get :generate_instance
      get :export
    end
    collection do
      get :get_form_fields
      get :get_field_aliases
      get :get_field_basic_types
    end
  end

  resources :notifications, only: [:index] do
    collection do
      post :mark_all_as_read
      get :mark_as_read
    end
  end

  resources :hour_types
  resources :hours do
    resources :comments
  end

  get 'show_patients_forms' => 'admin_patients#show_patients_forms', as: 'show_patients_forms'
  
  resources :admin_configurations, only: [:index, :update]

  namespace :admin do
    get :users
    put :update_users_roles_permissions
    get :patients
    put :update_patients_roles_permissions
    put :timesheets
    put :update_timesheets_roles_permissions
    get :visits
    put :update_visits_roles_permissions
    get :bills
    put :update_bills_roles_permissions
  end

  resources :coverage_areas

  resources :agencies

  resources :visits do
    resources :comments
    get :add_reimbursement
  end

  resources :visit_types

  resources :reimbursements

  resources :diseases

  resources :departments

  get 'reports/get_total_report'

  get 'create_timesheet' => "timesheets#create_timesheet", as: 'create_timesheet'

  mount CustomForms::Engine => '/'

  get 'timesheets/update_task_state', as: 'update_task_state'

  get 'timesheets/latest' => 'timesheets#show_latest', as: 'latest_timesheet'
  get 'employees_timesheets' => 'timesheets#employees_timesheets', as: 'employees_timesheets'
  
  resources :timesheets, only: [:index, :show, :update] do
    resources :comments
    member do
      put :submit
      put :admit
      put :pay
      get :send_email_to_owner
    end
  end
  put 'timesheets' => 'timesheets#index' 
  resources :payrolls do 
    member do
      get 'payroll_statistics/get_exceeded_employees', as: 'get_exceeded_employees'
      get 'payroll_statistics/show_employees_visits_per_patient', as: 'show_employees_visits_per_patient'
      get 'payroll_statistics/show_top_ten_employees', as: 'show_top_ten_employees'
      get 'payroll_statistics/show_employees_with_reimb', as: 'show_employees_with_reimb'
      get 'payroll_statistics/show_employees_with_over_time', as: 'show_employees_with_over_time'
      
    end
  end

  resources :roles

  resources :user_documents

  resources :document_types

  get 'admin/index'

  resources :license_types

  resources :job_types

  get "find_patients_matches" => "patients#find_patients_matches", as: "find_patients_matches"
  get 'patients/delete_all_patients' => 'patients#delete_all_patients', as: "delete_all_patients"
  resources :patients do
    put :update_forms, on: :member
    get :get_patient_data
  end

  get 'scrape_users' => 'users#scrape_users'
  get 'scrape_agencies' => 'agencies#scrape_agencies'
  get 'scrape_patients' => 'patients#scrape_patients'
  get 'scrape_visits' => 'visits#scrape_visits'

  root 'users#index'
  devise_for :users, controllers: { registrations: 'users' }
  resources :users, except: :destroy do
    put :update_forms, on: :member
    post :reset_password_via_email
    resources :timesheets, only: [:index, :show, :update] do
      member do
        put :submit
        put :admit
        put :pay
      end
    end
    member do
      post :deactivate_user
      post :activate_user
      put :update_password
    end
    resources :visits
  end

  get 'edit_roles' => 'users#edit_user_roles', as: 'edit_user_roles'
  put 'update_user_role' => 'users#update_user_role', as: 'update_user_role'

  get 'view_assigned_visits' => 'visits#view_assigned_visits', as: 'view_assigned_visits'
  get 'get_visit_type_dependant_data' => 'visit_types#get_visit_type_dependant_data', as: 'get_visit_type_dependant_data'

  get 'static_page/:page' => 'static#show'
  get 'show_comments' => 'visits#show_comments'

end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  before_action :set_report, only: [:show, :edit, :update, :destroy, :generate_instance]

  # GET /reports
  # GET /reports.json
  def index
    @reports = Report.all
  end

  # GET /reports/1
  # GET /reports/1.json
  def show
  end

  # GET /reports/new
  def new
    @report = Report.new
    @report.report_fields.build
  end

  # GET /reports/1/edit
  def edit
    search_field = @report.report_fields.first.field_type
    set_field_types(search_field, @report.custom_form_id)

    set_field_aliases(search_field,  @report.custom_form_id, @report.report_fields.last.field_type_ids.uniq)
  end

  # POST /reports
  # POST /reports.json
  def create
    @report = Report.new(report_params)

    respond_to do |format|
      if @report.save
        format.html { redirect_to reports_path, notice: 'Report was successfully created.' }
        format.json { render :show, status: :created, location: @report }
      else
        format.html { render :new }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reports/1
  # PATCH/PUT /reports/1.json
  def update
    respond_to do |format|
      if @report.update(report_params)
        format.html { redirect_to reports_path, notice: 'Report was successfully updated.' }
        format.json { render :show, status: :ok, location: @report }
      else
        format.html { render :edit }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reports/1
  # DELETE /reports/1.json
  def destroy
    @report.destroy
    respond_to do |format|
      format.html { redirect_to reports_path, notice: 'Report was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def generate_instance
    respond_to do |format|
      format.html
      format.json { render json: ReportInstanceDatatable.new(view_context)}
      format.xls 
    end
  end

  def export
    @report = Report.includes(:report_fields).find(params[:id])
    @data = Report.report_data(params)
    data = Spreadsheet::Workbook.new
    filename = "#{@report.name}_#{Date.today.strftime('%d_%m_%Y')}.xls"
    respond_to do |format|
      format.xls { send_data(Report.to_csv(@data), filename: filename) }
    end
  end

  def get_search_field(field_type = params[:field_type])
    search_field = if field_type.start_with?("date"  )
      "date"
    else
      field_type
    end
    search_field
  end

  # get field types for report by custom form & field type
  def get_form_fields
    search_field = get_search_field(params[:field_type])
    set_field_types(search_field, params[:custom_form_id])
    respond_to do |format|
      format.js
    end
  end

  def get_field_aliases
    report_field_aliases(params[:field_type], params[:custom_form_id], params[:field_aliases_ids])
    respond_to do |format|
      format.js
    end
  end

  # get field basic types by custom form 
  def get_field_basic_types
    custom_form = CustomForms::CustomForm.find(params[:custom_form_id])
    @basic_field_types = custom_form.basic_field_types
    respond_to do |format|
      format.js
    end
  end

  private


    # prepare report field aliases 
    def report_field_aliases(field_type, custom_form_id, field_aliases_ids)
      search_field = get_search_field(field_type)
      set_field_aliases(search_field, custom_form_id, field_aliases_ids)
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_report
      @report = Report.includes(:report_fields).find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def report_params
      params.require(:report).permit(:custom_form_id, :name,
                                    report_fields_attributes:
                                    [:id, :field_type, :field_value, field_type_ids: [], 
                                    field_aliases: [], value_options: [:from, :to, :days, :include_empty]])
    end

    # get field types records by custom_form_id and filed type
    def set_field_types(search_field, custom_form_id)
      @field_types = CustomForms::CustomForm.find(custom_form_id).form_sections.
                                            map(&:section_fields).flatten.map(&:field_type).
                                            select{|f| f.field_type == search_field}.uniq
    end

    def set_field_aliases(search_field, custom_form_id, field_aliases_ids = nil)
      section_fields = CustomForms::CustomForm.find(custom_form_id).form_sections.map(&:section_fields)
      field_type_ids = section_fields.flatten.map(&:field_type).select{|f| f.field_type == search_field}.map(&:id)
      @field_aliases = section_fields.flatten.select{|f| field_type_ids.include?f.field_type_id}
      if field_aliases_ids
        @field_aliases = @field_aliases.select{|f| field_aliases_ids.map(&:to_s).include?f.field_type_id.to_s}
      end
      @field_aliases.uniq
    end
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/views/reports/_aliases_selector.html.haml
- @field_aliases ||= []
%label{class: "col-sm-1 control-label"}
  Fields Aliases
.col-sm-11
  = f.select :field_aliases, options_from_collection_for_select(@field_aliases, :field_alias, :field_alias, f.object.field_aliases), {}, { multiple: true, id: 'field_aliases' }

app/views/reports/_field_selector.html.haml
- @field_types ||= []
%label{class: "col-sm-1 control-label"}
  Field Types
.col-sm-11
  = f.select :field_type_ids, options_from_collection_for_select(@field_types, :id, :humanized_name, f.object.field_type_ids), {}, { multiple: true, id: 'field_type_ids' }

app/views/reports/_form.html.haml
= form_for @report do |f|
  - if @report.errors.any?
    #error_explanation
      %h2= "#{pluralize(@report.errors.count, "error")} prohibited this report from being saved:"
      %ul
        - @report.errors.full_messages.each do |msg|
          %li= msg

  .form-horizontal
    .form-group
      = f.label :Name, class: "col-sm-1 control-label text-right"
      .col-sm-11
        = f.text_field  :name, class: 'form-control'
        .form-control-line

    .form-group
      = f.label "Custom Form", class: "col-sm-1 control-label text-right"
      .col-sm-11
        = f.select :custom_form_id, options_from_collection_for_select(CustomForms::CustomForm.all, :id, :title, @report.custom_form_id), {:include_blank => true}, {class: "form-control custom_form_select"}

    
  = f.fields_for :report_fields, @report.report_fields do |builder|
    = render 'report_field_form_row', f: builder, field_type_id: "1"
      
  - content_for :footer do
    - action = f.object.persisted? ? 'Save' : 'Submit'
    = section_submit_action action, f.options[:html][:id]
    = section_action "reply", reports_path, "Report"

app/views/reports/_report_field_form_row.html.haml
/ - fields = [['boolean', 'Boolean'], ['date_interval', 'Date interval'], ['date', 'Date (expires in x days)'], ['expirable_file', 'Expirable file'], ['file', 'File']]
-if @report.custom_form
  - fields = @report.custom_form.basic_field_types.map{|field| [field, field.titleize]}
- else
  - fields = []
  
.form-horizontal
  .form-group
    = f.label :field_type, { class: "col-sm-1 control-label text-right" }
    .col-sm-11
      = f.collection_select :field_type, fields, :first, :last, {}, { class: "form-control field_type_select", "data-id": "#{field_type_id}" }
.form-horizontal
  .form-group
    = render 'field_selector', f: f

.form-horizontal
  .form-group
    = render 'aliases_selector', f: f

  .form-horizontal

    = f.fields_for :value_options, OpenStruct.new(f.object.value_options) do |value_option|
      .form-group.days_fields.option_fields{class: "#{'hidden' if !['date', 'expirable_file'].include?f.object.field_type }" }
        = value_option.label :days, { class: "col-sm-1 control-label text-right" }
        .col-sm-11
          = value_option.text_field :days, class: "form-control numbers_only"
      .form-group.interval_fields.option_fields{class: "#{'hidden' if f.object.field_type != 'date_interval'}" }
        = value_option.label :from, { class: "col-sm-1 control-label text-right" }
        .col-sm-11
          = value_option.text_field :from, class: "form-control datePickerField"
      .form-group.interval_fields.hidden.option_fields
        = value_option.label :to, { class: "col-sm-1 control-label text-right" }
        .col-sm-11
          = value_option.text_field :to, class: "form-control datePickerField"
      .form-group.boolean_fields.option_fields{class: "#{'hidden' if f.object.field_type != 'boolean'}" }
        = f.label :field_value, { class: "col-sm-1 control-label text-right" }
        .col-sm-11
          = f.select :field_value, [[true, '1'], [false, '0']], {}, { class: "form-control" }

- if f.object.field_type != 'boolean'
  .form-horizontal
    .form-group.include_empty_container
      = f.fields_for :value_options, OpenStruct.new(f.object.value_options) do |value_option|
        = render 'reports/query_fields/blank_flag', option: value_option

app/views/reports/edit.html.haml
.section-body
  .row 
    .col-md-12
      .card
        .card-head.style-primary
          %header.text-xl 
            Editing report
  .card
    .card-body          
      = render 'form'

app/views/reports/generate_instance.html.haml
.section-body
  .row
    .col-md-12
      .card
        .card-head.style-primary
          %header.text-xl
            = @report.name
          .tools
            = link_to '', export_report_path(@report,format: "xls", remote: true), class: 'pull-right btn btn-floating-action ink-reaction btn-info  btn-xs fa fa-file-excel-o'
  .card.card-underline
    .card-body
      .table-responsive
        %table.table.table-condensed.text-xs#reports_table
          %thead
            %tr
              %th Name
              %th Document Title
              %th Document/Expiry Date
              %th Summary
          %tbody

:javascript
  $(function(){
    columns = [
            {data :'model'},
            {data :'field', class: 'text-right'},
            {data :'value'},
            {data :'count'}
        ]

    var datatable_handler = new DataTableHandler('/reports/#{params[:id]}/generate_instance', 'bill', '#reports_table', [], [], columns, {showButtons: false, "ordering": false});

    $('#reports_table').rowGrouping({bExpandableGrouping: true, asExpandedGroups: ['dd']});
  });
  

app/views/reports/get_field_aliases.js.haml
$("#field_aliases").empty()
- @field_aliases.each do |field_alias|
  $("#field_aliases").append("<option value='#{field_alias.field_alias}'>#{field_alias.field_alias}</option>")
$("#field_aliases").select2("val", "");

app/views/reports/get_field_basic_types.js.haml
$('select.field_type_select').empty()
- @basic_field_types.each do |basic_field_type|
  $("select.field_type_select").append("<option value='#{basic_field_type}'>#{basic_field_type.titleize}</option>")
$('select.field_type_select').select2("val", "");

app/views/reports/get_form_fields.js.haml
$("#field_type_ids").empty()
- @field_types.each do |field_type|
  $("#field_type_ids").append("<option value='#{field_type.id}'>#{field_type.humanized_name}</option>")
$("#field_type_ids").select2("val", "");

app/views/reports/get_total_report.html.haml
.row
  .col-md-12
    .card
      .card-head.style-primary
        %header
          .text-xl
            Reports
.row
  .col-md-12.col-lg-12.col-sm-12
    .card
      .card-body          
        %table.table
          %thead
            %tr
              %td
              %td
          %tbody
            %tr
              %td
                Total Number of form categories is 
              %td= @categories_count
            %tr
              %td
                Total Number of custom forms is 
              %td= @custom_forms_count
            - @categories_custom_forms_count.each do |name, count|
              %tr
                %td 
                  - if name.nil?
                    uncategorized
                  - else
                    = name
                %td
                  = count
            %tr
              %td
                Total Number of users is 
              %td= @users_count
            %tr
              %td
                Total Number of disciplines is 
              %td= @disciplines_count
      

app/views/reports/index.html.haml
.section-body
  .card
    .card-body
      %table.table.datatableAutoInitializer
        %thead
          %tr
            %th Name
            %th Schema
            %th Field
            %th Query
            %th

        %tbody
          - @reports.each do |report|
            %tr
              %td= report.name.humanize
              %td= CustomForms::CustomForm.find(report.custom_form_id).title.humanize if report.custom_form_id
              - field_type = report.report_fields.first.field_type
              %td= field_type.humanize
              %td
                - if field_type == "boolean"
                  - field_value = report.report_fields.first.field_value
                  = !field_value.to_i.zero?
                - elsif field_type == "date_interval"
                  - field_value = report.report_fields.first.value_options
                  = "#{field_value['from']}:#{field_value['to']}"
                - elsif ["date", 'expirable_file'].include? field_type 
                  - field_value = report.report_fields.first.value_options
                  = "Report date range: #{field_value['days']} day(s)"


              %td
                .pull-right
                  = link_to '', generate_instance_report_path(report), class: "btn btn-floating-action ink-reaction  btn-xs fa fa-eye text-primary "
                  = link_to '', edit_report_path(report), class: "btn btn-floating-action ink-reaction  btn-xs fa fa-edit text-primary"
                  = link_to '', '', class: "btn btn-floating-action ink-reaction  btn-xs fa fa-trash text-primary swal swal-delete"
                  = link_to '', report, :method => :delete

- content_for :footer do
  = section_floating_action "plus", new_report_path, "Add New Report"

- content_for :header_title do 
  Listing reports

app/views/reports/new.html.haml
.section-body
  .card
    .card-body
      = render 'form'

- content_for :header_title do 
  New report

app/views/reports/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @report.name
%p
  %b Custom form:
  = @report.custom_form_id

= link_to 'Edit', edit_report_path(@report)
\|
= link_to 'Back', reports_path
\|
= link_to 'Generate report', generate_instance_report_path(@report)